set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ',tmux-256color:RGB'

# Cambiar PREFIX a Ctrl + a, mas comodo.
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# actualizar barra cada 300 segundos
set -g status-interval 300

set-option -sg escape-time 10

setw -g mode-keys vi

# historial
set -g history-limit 10000

# no cambiar nombre a pestana
set-option -g visual-activity on
set-window-option -g monitor-activity on
set-option -g allow-rename off

set -g focus-events on
