set -g @load_base 1
set -g @load_keys 1
set -g @load_status 1
set -g @load_plugins 1

if -F '#{==:#{@load_base},1}' "source-file ~/.configuracion/tmux/base.conf"
if -F '#{==:#{@load_keys},1}' "source-file ~/.configuracion/tmux/keys.conf"
if -F '#{==:#{@load_status},1}' "source-file ~/.configuracion/tmux/status.conf"
if -F '#{==:#{@load_plugins},1}' "source-file ~/.configuracion/tmux/plugins.conf"
